[project]
name = "pythonstoreapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "yousefalhamad9@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "beanie==1.25.0",
    "fastapi[standard]>=0.141.1",
    "motor==3.3.2",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.13.0",
    "pymongo==4.6.1",
]

[project.scripts]
pythonstoreapi = "pythonstoreapi:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
